// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TDRevision.Models.EntityFramework;

#nullable disable

namespace TDRevision.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TDRevision.Models.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("COM_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCommande"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("UTI_ID");

                    b.Property<string>("Montant")
                        .HasColumnType("text")
                        .HasColumnName("COM_MONTANT");

                    b.Property<string>("NomArticle")
                        .HasColumnType("text")
                        .HasColumnName("COM_NOMARTICLE");

                    b.HasKey("IdCommande")
                        .HasName("COM_ID");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("T_E_COMMANDE_COM", "public");
                });

            modelBuilder.Entity("TDRevision.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UTI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<int>("CodePostal")
                        .HasMaxLength(5)
                        .HasColumnType("integer")
                        .HasColumnName("UTI_CODEPOSTAL");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("UTI_NOM");

                    b.Property<string>("NumeroRue")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("UTI_NUMERORUE");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("UTI_PRENOM");

                    b.Property<string>("Rue")
                        .HasColumnType("text")
                        .HasColumnName("UTI_RUE");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("UTI_VILLE");

                    b.HasKey("IdUtilisateur")
                        .HasName("UTI_ID");

                    b.ToTable("T_E_UTILISATEUR_UTI", "public");
                });

            modelBuilder.Entity("TDRevision.Models.Commande", b =>
                {
                    b.HasOne("TDRevision.Models.Utilisateur", "CommandeNav")
                        .WithMany("Commandes")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UTI_ID");

                    b.Navigation("CommandeNav");
                });

            modelBuilder.Entity("TDRevision.Models.Utilisateur", b =>
                {
                    b.Navigation("Commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
